# Generated by Django 2.2.2 on 2019-06-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
